name: Executar Testes API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        working-directory: API
        run: npm install

      - name: Executar testes da API
        working-directory: API
        run: npm test

      - name: Salvar relatório HTML dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-api
          path: API/reports
          if-no-files-found: ignore